import pygame

TURTLE_AMOUNT = 4
ARRAY_SIZE = 21

EMPTY = 'EMPTY'
BAG = 'BAG'
CAN = 'CAN'
BOTTLE = 'BOTTLE'
TRASH_LIST = [EMPTY, BAG, CAN, BOTTLE]

# TURTLE BOT:
START_X = 10

STEP = 1
UP = 'UP'
DOWN = 'DOWN'
LEFT = 'LEFT'
RIGHT = 'RIGHT'

# GAME:
START_TIME_BETWEEN_TRASH = 2
TIME_BETWEEN_DIFF = 5
MAX_DIFF = 7
START_DIFF = 1

# SCREEN:
FPS = 60
WINDOW_WIDTH, WINDOW_HEIGHT = 420, 400
WINDOW = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))